# Generated by Django 5.2.8 on 2025-11-15 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classschedule',
            name='room',
        ),
    ]
